name: test-py39-functional-microshift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHONWARNINGS: ignore
  KUBECONFIG: ${{ github.workspace }}/kubeconfig
  ACCT_MGT_VERSION: "6012025c247ab25fb2cab3be9ad06080e28713ee"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Fix for "grup-efi-amd64-signed" missing
        run: |
          sudo apt-mark hold grub-efi-amd64-signed

      - name: Upgrade and install packages
        run: |
          bash ./ci/setup-ubuntu.sh

      - name: Install oc/kubectl clients
        run: |
          bash ./ci/setup-oc-client.sh

      - name: Install Microshift
        run: |
          ./ci/microshift.sh

      - name: Install ColdFront and plugin
        run: |
          ./ci/setup.sh

      - name: Run functional tests
        run: |
          ./ci/run_functional_tests_openshift.sh
